name = "ComodoFerrite"
uuid = "4ccf3a29-4aa4-4027-a3be-f1f903a96b6c"
authors = ["Aminofa70 <amin.alibakhshi@upm.es> and contributors"]
version = "1.0.0-DEV"

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
Ferrite = "1.1.0"
OrderedCollections = "1.8.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
