name: Documentation

on:
  push:
    branches:
      - main  # Change to your default branch name if not "main"
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push to gh-pages branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'  # Match your local Julia version

      - name: Cache Julia packages
        uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-artifacts-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

      - name: Install dependencies
        run: |
          julia --project=docs -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'

      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs docs/make.jl